name: Auto Commit

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto-commit by GitHub Actions"
          git push
